files:
  - source: /**/*.md
    ignore:
      - README.Makefile.md
    translation: /%locale_with_underscore%/%original_path%/%original_file_name%
  - source: /**/*.png
    translation: /%locale_with_underscore%/%original_path%/%original_file_name%
  - source: /**/*.gif
    translation: /%locale_with_underscore%/%original_path%/%original_file_name%
  - source: /**/*.jpg
    translation: /%locale_with_underscore%/%original_path%/%original_file_name%
